### ISSUE TITLE
Wrist motor issue at PS2_Control.ino

### ISSUE THREAD

**Issue by kimbring2** [Lynxmotion/Arms#2]
Hello,

I built the AL5D and tested it using the code here using PS2 controller. But, there is a problem that the wrist motor moved slowly without any command.

At first I thought it is not a different problem. However, the wrist motor broke down eventually.
The problem is that same phenomena occurs after changing broken motor to new one.

After the failure, I can not be used code because of breakdown. Is this a phenomenon that only I suffer? 

P.S. The same problem does not occur when testing with other code.

Thank you,
From Dohyeong

**Comment by rbscharette** [comment]
Hi Dohyeong,

Please post about your issue [here](https://www.robotshop.com/community/forum/c/lynxmotion/robot-arms/24). Also include more details about your setup, such as exactly which code you are using (direct links) for the AL5D code and the PS2 library and some pictures of the physical setup.

Sincerely,

**Comment by kimbring2** [comment]
Hi, Rbscharette

Thank you for response. 
I am going to upload my problem to that link with detailed information.

Sincerely
